import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { SearchBox } from '@/components/searchBox/SearchBox';
import { DockBar } from '@/components/dockBar/Dockbar';
import { SearchButton } from '@/components/shared/SearchButton';
import { BackgroundContainer } from '@/components/shared/BackgroundContainer';
import { BackGroundSetting } from '@/components/backgroundSettings/BackgroundSettings';
import { ContextMenu } from '@/components/shared/ContextMenu';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh`}
      >
        <SearchButton />
        <SearchBox />
        <BackgroundContainer>
          {children}
          <BackGroundSetting />
        </BackgroundContainer>
        <ContextMenu />
        <DockBar />
      </body>
    </html>
  );
}
